# this file is for jarngreipr.

[general]
file_prefix = "example1"
output_path = "./"
parameters  = "./parameter/parameters.toml"
boundary    = "Unlimited"
precision   = "double"
thread      = false
gpu         = false
seed        = 2374

[[structures]]
# A-D means [A, B, C, D]. A&C&E means [A, C, E]. A&C-E means [A, C, D, E].
A-D = {file = "./data/pdb/example.pdb", model = "CarbonAlpha"}
# A-D = {file = "./data/pdb/example.pdb", model = "CarbonAlpha"}
# or
# A = {file = "./data/pdb/something1.pdb", model = "CarbonAlpha"}
# B = {file = "./data/pdb/something2.pdb", model = "CarbonAlpha"}
# C = {file = "./data/pdb/something3.pdb", model = "CarbonAlpha"}
# D = {file = "./data/pdb/something4.pdb", model = "CarbonAlpha"}
#
# To specify the initial conformation that is differrent from reference
# structure, define `initial`.
# A-D = {file = "./data/pdb/example.pdb", initial = "./data/pdb/example2.pdb", model = "CarbonAlpha"}

[[simulators]]
scheme     = "Underdamped Langevin"
delta_t    = 0.4    # the unit [tau] depends on the forcefield and parameters
total_step = 50_000 # the total simulation time will be 0.4 * 50000 = 20000.
save_step  = 100    # each 40 [tau], the configurations are saved.

[[systems]]
temperature    = 300.0       # [K]
ionic_strength = 0.1         # [mol/L]
boundary       = {}
# boundary     = {lower = [0.0, 0.0, 0.0], upper = [10.0, 10.0, 10.0]}

[[forcefields]]

[forcefields.local] # contains local forcefield.

# the energy become the sum of these.
A-D = [{name = "ClementiGo"},]
# or
# A = ["AICG_2_plus"]
# B = ["AICG_2_plus"]
# C = ["AICG_2_plus"]
# D = ["AICG_2_plus"]

[forcefields.global] # contains global forcefield.
A-D = [{name = "GoContact"}, {name = "ExcludedVolume"}]
# or
# "A&B" = [{name = "GoContact"}, {name = "ExcludedVolume"}]
# "A&C" = [{name = "GoContact"}, {name = "ExcludedVolume"}]
# "A&D" = [{name = "GoContact"}, {name = "ExcludedVolume"}]
# "B&C" = [{name = "GoContact"}, {name = "ExcludedVolume"}]
# "B&D" = [{name = "GoContact"}, {name = "ExcludedVolume"}]
# "C&D" = [{name = "GoContact"}, {name = "ExcludedVolume"}]
