dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-5"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
        - libboost-test-dev
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-3.7"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7
        - build-essential
        - cmake
        - libboost-test-dev
  - os: osx
    language: cpp
    compiler: clang

install:
- git submodule init
- git submodule update

script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
- make
- make test
- ./src/mjolnir ../input/sh3_AICG2+.toml
- ./src/mjolnir ../input/sh3_AICG2+_periodic.toml
